//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayaki.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bayaki.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap GPXLoader_ICON {
            get {
                object obj = ResourceManager.GetObject("GPXLoader_ICON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   GPXLoader に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GPXLoader_NAME {
            get {
                return ResourceManager.GetString("GPXLoader_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap HeaderSeed {
            get {
                object obj = ResourceManager.GetObject("HeaderSeed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   AIzaSyDlepDvnD6x9Fkm-5l9IfqiH12kZiiO78g に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KEY_GOOGLE {
            get {
                return ResourceManager.GetString("KEY_GOOGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   dj0zaiZpPUpJRmx2aEp4RUwyMyZzPWNvbnN1bWVyc2VjcmV0Jng9MDM- に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KEY_YAHOO {
            get {
                return ResourceManager.GetString("KEY_YAHOO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap KMLLoader_ICON {
            get {
                object obj = ResourceManager.GetObject("KMLLoader_ICON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   KMLLoader に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KMLLoader_NAME {
            get {
                return ResourceManager.GetString("KMLLoader_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除してもよいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG1 {
            get {
                return ResourceManager.GetString("MSG1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   位置情報元の保存ファイルを読み込めませんでした。\n再起動して解決しない場合はマイドキュメント フォルダにある「Bayaki Folder\BayakiSummary.dat」を削除してから再起動してみてください。。\n\n理由：\n{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG10 {
            get {
                return ResourceManager.GetString("MSG10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   plugin[{0}]でエラーが発生しました。\n\n詳細\n{1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG2 {
            get {
                return ResourceManager.GetString("MSG2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG3 {
            get {
                return ResourceManager.GetString("MSG3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プラグイン選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG4 {
            get {
                return ResourceManager.GetString("MSG4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   位置情報を削除しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG5 {
            get {
                return ResourceManager.GetString("MSG5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   二重起動はできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG6 {
            get {
                return ResourceManager.GetString("MSG6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}(記録開始) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG7 {
            get {
                return ResourceManager.GetString("MSG7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}(記録終了) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG8 {
            get {
                return ResourceManager.GetString("MSG8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択されたプラグインはインストール済みです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG9 {
            get {
                return ResourceManager.GetString("MSG9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skytraq Downloader に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SkytraqDownloader_NAME {
            get {
                return ResourceManager.GetString("SkytraqDownloader_NAME", resourceCulture);
            }
        }
    }
}
