//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPSBabelPlugin.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\GPSBabel\\gpsbabel.exe")]
        public string GPSBabel_PATH {
            get {
                return ((string)(this["GPSBabel_PATH"]));
            }
            set {
                this["GPSBabel_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-w -t -i skytraq,erase=0,baud=115200,initbaud=38400,no-output=0 -f COM6")]
        public string GPSBabel_Param0 {
            get {
                return ((string)(this["GPSBabel_Param0"]));
            }
            set {
                this["GPSBabel_Param0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GPSBabel_Param1 {
            get {
                return ((string)(this["GPSBabel_Param1"]));
            }
            set {
                this["GPSBabel_Param1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GPSBabel_Param2 {
            get {
                return ((string)(this["GPSBabel_Param2"]));
            }
            set {
                this["GPSBabel_Param2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GPSBabel_Param3 {
            get {
                return ((string)(this["GPSBabel_Param3"]));
            }
            set {
                this["GPSBabel_Param3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GPSBabel_Param4 {
            get {
                return ((string)(this["GPSBabel_Param4"]));
            }
            set {
                this["GPSBabel_Param4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GPSBabel_Param5 {
            get {
                return ((string)(this["GPSBabel_Param5"]));
            }
            set {
                this["GPSBabel_Param5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GPSBabel_Param6 {
            get {
                return ((string)(this["GPSBabel_Param6"]));
            }
            set {
                this["GPSBabel_Param6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GPSBabel_Param7 {
            get {
                return ((string)(this["GPSBabel_Param7"]));
            }
            set {
                this["GPSBabel_Param7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GPSBabel_Param8 {
            get {
                return ((string)(this["GPSBabel_Param8"]));
            }
            set {
                this["GPSBabel_Param8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GPSBabel_Param9 {
            get {
                return ((string)(this["GPSBabel_Param9"]));
            }
            set {
                this["GPSBabel_Param9"] = value;
            }
        }
    }
}
