//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyTraqPlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SkyTraqPlugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Configure_ICON {
            get {
                object obj = ResourceManager.GetObject("Configure_ICON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Skytraq
        ///Configuration に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Configure_NAME {
            get {
                return ResourceManager.GetString("Configure_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skytraq Download Data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DownloadData_DefaultName {
            get {
                return ResourceManager.GetString("DownloadData_DefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Downloader_ICON {
            get {
                object obj = ResourceManager.GetObject("Downloader_ICON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Skytraq
        ///logdata download に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Downloader_NAME {
            get {
                return ResourceManager.GetString("Downloader_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Eraser_ICON {
            get {
                object obj = ResourceManager.GetObject("Eraser_ICON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Skytraq
        ///logdata Erase に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Eraser_NAME {
            get {
                return ResourceManager.GetString("Eraser_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自動でポートを選択できませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG1 {
            get {
                return ResourceManager.GetString("MSG1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG10 {
            get {
                return ResourceManager.GetString("MSG10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   書き込み中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG11 {
            get {
                return ResourceManager.GetString("MSG11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ダウンロード失敗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG12 {
            get {
                return ResourceManager.GetString("MSG12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ダウンロード完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG13 {
            get {
                return ResourceManager.GetString("MSG13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ダウンロード中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG14 {
            get {
                return ResourceManager.GetString("MSG14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メートル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG15 {
            get {
                return ResourceManager.GetString("MSG15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   秒 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG16 {
            get {
                return ResourceManager.GetString("MSG16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開始前 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG17 {
            get {
                return ResourceManager.GetString("MSG17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   初期化処理 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG18 {
            get {
                return ResourceManager.GetString("MSG18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   読出処理 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG19 {
            get {
                return ResourceManager.GetString("MSG19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG2 {
            get {
                return ResourceManager.GetString("MSG2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変換処理 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG20 {
            get {
                return ResourceManager.GetString("MSG20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再起動 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG21 {
            get {
                return ResourceManager.GetString("MSG21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データはありませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG3 {
            get {
                return ResourceManager.GetString("MSG3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skytraqの接続に失敗しました
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG4 {
            get {
                return ResourceManager.GetString("MSG4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Logデータを消去します。
        ///よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG5 {
            get {
                return ResourceManager.GetString("MSG5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   消去しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG6 {
            get {
                return ResourceManager.GetString("MSG6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   消去できませんでした。\n・ポートがあっていますか？
        ///・電源はONになっていますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG7 {
            get {
                return ResourceManager.GetString("MSG7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ephemerisを書き込みました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG8 {
            get {
                return ResourceManager.GetString("MSG8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ephemerisを書き込みできませんでした に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG9 {
            get {
                return ResourceManager.GetString("MSG9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自動 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PORT_AUTOSEL {
            get {
                return ResourceManager.GetString("PORT_AUTOSEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap SetEphemeris_ICON {
            get {
                object obj = ResourceManager.GetObject("SetEphemeris_ICON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Skytraq
        ///Set Ephemeris に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SetEphemeris_NAME {
            get {
                return ResourceManager.GetString("SetEphemeris_NAME", resourceCulture);
            }
        }
    }
}
